version: "3"

services:
  mongo:
    image: mongo:3.2
    restart: always
    ports:
      - 27017:27017
    container_name: mongo
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - ./mongodb:/data/db

  mongo-express:
    image: mongo-express:0.45
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456