server:
  port: 8080
  #jpa打印出sql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jwt-demo?useUnicode=true&characterEncoding=utf8&userSSL=false
    username: root
    password: adminadmin
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#白名单方法
jwt:
  whiteLists: /index/login,/index/say/hello,/favicon.ico