spring:
  datasource:
    name: mybatits_plus
    url: jdbc:mysql://127.0.0.1:3306/student?useUnicode=true&characterEncoding=utf8
    username: root
    password: adminadmin
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

# 配置slq打印日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl